---
title: "eval-grades_DROGO"
author: "Louis DROGO"
format: html
editor: visual
---


```{r}
#| message: false
#| echo: false

library(ggplot2)
library(dplyr)
library(tidyr)
library(lubridate)
library(vroom)
library(here)

here::i_am("eval-grades.Rproj")
```


# I - Introduction

## 1. Study Organisation

### Question 1

```{r}
courses <- vroom("Data/courses.csv",delim = ",", show_col_types = FALSE)
```

### Question 2

```{r}
#| echo: false
courses |>
  arrange(course)|>
  rename("course name"=course,
         "identifier"=course_id,
         "number of exam"=nb_grades)|>
  knitr::kable()
```


## 2. Students

### Question 3

```{r}
#| echo: false
students <- vroom("Data/students.csv",delim = ",",show_col_types = FALSE)
students$sex <- as.factor(students$sex)
sapply(students, class)
```
## 3. Graddes

### Question 4

```{r}
#| warning: false
grades <- vroom("Data/grades.csv",delim = "|",na=c("$"),show_col_types = FALSE)
grades$grade <- as.numeric(grades$grade)
```


# II - Population

### Question 5

```{r}
students |>
  group_by(group)|>
  summarise(count=n())|>
  ggplot(aes(x=group,y=count))+
  geom_col()+
  labs(title = "Number of Students per Group",x = "Group Number",y = "Number of Students")
```


### Question 6

```{r}
students |>
  group_by(group,sex)|>
  summarise(count=n(),.groups = "drop")|>
  ggplot(aes(x=group,y=count,fill = sex))+
  geom_col()+
  labs(title = "Gender balance per Group",x = "Group Number",y = "Number of Students")
```


### Question 7

```{r}
students <- students |>
  mutate(age=time_length(today()- birth_date, unit="year"))

students$age <- round(students$age) # I round every age to the closest integer

students |>
  ggplot(aes(x=age))+
  geom_histogram(binwidth = 1, color = "white")+
  labs(title = "Distribution of Student Age",x = "Age (Years)",y = "Density / Count")+
  theme_minimal()
```


### Question 8

```{r}
students |>
  group_by(group)|>
  summarise(median=round(median(age)))|>
  knitr::kable()
```

### Question 9

```{r}
students|>
  group_by(group)|>
  slice_max(order_by = age, n = 1, with_ties = FALSE)|>
  select(id, sex, age, group)|>
  arrange(desc(age))|>
  knitr::kable()
```


# III - Simple grade analysis

### Question 10

```{r}
nb_grades <- grades |>
  filter(!is.na(grade))|>
  nrow()
nb_grades
```

The data set contains **`r nb_grades`** grades.

### Question 11

```{r}
course_id11 <- courses |>
  filter(course == "Engineering and Technology of the Roman Empire") |>
  pull(course_id)

avg_grades <- grades |>
  filter(course_id == course_id11, !is.na(grade)) |>
  left_join(students |> select(id, group), by = "id") |>
  group_by(group) |>
  summarise(average_grades = mean(grade, na.rm = TRUE), .groups = "drop")

ggplot(avg_grades, aes(x = group, y = average_grades)) +
  geom_col()

```

### Question 12

```{r}
grades |>
  left_join(courses %>% select(course_id, trimester), by = "course_id") |>
  filter(!is.na(grade), !is.na(trimester)) |>
  mutate(trimester = as.factor(trimester)) |>
  ggplot(aes(x = grade)) + 
    geom_histogram(binwidth = 1, color = "white") +
    facet_wrap(~ trimester, scales = "free_y", ncol = 3)+
  labs(title = "Distribution of grades per trimester",x = "Grades",y = "Number of obs")
```


# V - Attendance analysis

### Question 13

```{r}
grades |>
  filter(!is.na(grade)) |>
  left_join(students |> select(id,group,sex), by = "id")|>
  group_by(id,group,sex) |>
  summarise(nb_grades = n(), .groups = 'drop')|>
  slice_tail(n=5)|>
  knitr::kable()
```


### Question 14

```{r}
grades |>
  filter(!is.na(grade)) |>
  left_join(students |> select(id,group,sex), by = "id")|>
  group_by(id,group,sex) |>
  summarise(nb_grades = n(), .groups = 'drop')|>
  ggplot(aes(x = nb_grades, fill = sex)) +
  geom_density(alpha = 0.6)
```





